"""Offline true-world survival measurement for recovery authority.

This module deliberately has no live-belief mutation API. It evaluates known exact
Showdown states against the isolated mechanics-reachability boundary and treats only
EXHAUSTIVELY_DISPROVED as exclusion evidence. WITNESSED, UNRESOLVED, and UNSUPPORTED
all preserve the true hidden world.

The harness is not the independent differential validator planned later in the
roadmap: fixture observations may be generated by the same pinned Showdown runtime.
Its purpose is to measure whether our own exclusion authority can ever reject a
known-real hidden world and to serialize any such failure as a deterministic hard
case.
"""

from __future__ import annotations

import hashlib
import json
import os
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Any, Callable, Iterable, Protocol

from champions_practice.reachability import (
    PublicReachabilityStep,
    ReachabilityResult,
    ReachabilityStatus,
    evaluate_deterministic_public_transition,
)


class RecoverySoundnessError(RuntimeError):
    """Offline soundness measurement could not continue safely."""


class SoundnessWorker(Protocol):
    def branch_many(
        self,
        *,
        state: dict[str, Any],
        branches: list[dict[str, Any]],
    ) -> list[dict[str, Any]]: ...


@dataclass(frozen=True)
class TrueWorldTransition:
    """One public transition generated from a known exact hidden world."""

    case_id: str
    source: str
    side: str
    pre_state: dict[str, Any]
    p1_choice: str
    p2_choice: str
    actual_public_view: dict[str, Any]
    actual_rng_seed: str | None
    probe_rng_seed: str | None
    actual_rng_draw_count: int | None = None
    previews: dict[str, list[str]] | None = None

    def __post_init__(self) -> None:
        if not isinstance(self.case_id, str) or not self.case_id.strip():
            raise ValueError("true-world transition requires a case_id")
        if not isinstance(self.source, str) or not self.source.strip():
            raise ValueError("true-world transition requires a source")
        if self.side not in {"p1", "p2"}:
            raise ValueError("true-world transition side must be p1 or p2")
        if not isinstance(self.pre_state, dict) or not self.pre_state:
            raise ValueError("true-world transition requires an exact pre_state")
        for label, choice in (
            ("p1_choice", self.p1_choice),
            ("p2_choice", self.p2_choice),
        ):
            if not isinstance(choice, str) or not choice.strip():
                raise ValueError(
                    f"true-world transition requires non-empty {label}"
                )
        if not isinstance(self.actual_public_view, dict):
            raise ValueError(
                "true-world transition requires an actual public view"
            )
        for label, seed in (
            ("actual_rng_seed", self.actual_rng_seed),
            ("probe_rng_seed", self.probe_rng_seed),
        ):
            if seed is not None and (
                not isinstance(seed, str) or not seed.strip()
            ):
                raise ValueError(f"{label} must be None or a non-empty string")
        if self.actual_rng_draw_count is not None and (
            isinstance(self.actual_rng_draw_count, bool)
            or not isinstance(self.actual_rng_draw_count, int)
            or self.actual_rng_draw_count < 0
        ):
            raise ValueError(
                "actual_rng_draw_count must be a non-negative integer or None"
            )

    @property
    def state_fingerprint(self) -> str:
        return _sha256_json(self.pre_state)


@dataclass(frozen=True)
class TrueWorldTransitionOutcome:
    """Reachability authority result for one known-real transition."""

    transition: TrueWorldTransition
    result: ReachabilityResult

    @property
    def survived(self) -> bool:
        return not self.result.establishes_impossibility

    @property
    def false_exclusion(self) -> bool:
        return self.result.establishes_impossibility


@dataclass(frozen=True)
class RecoverySoundnessReport:
    """Aggregate true-world survival metric over known-real transitions."""

    outcomes: tuple[TrueWorldTransitionOutcome, ...]

    @property
    def total(self) -> int:
        return len(self.outcomes)

    @property
    def survived(self) -> int:
        return sum(outcome.survived for outcome in self.outcomes)

    @property
    def false_exclusions(self) -> int:
        return sum(outcome.false_exclusion for outcome in self.outcomes)

    @property
    def witnessed(self) -> int:
        return sum(
            outcome.result.status is ReachabilityStatus.WITNESSED
            for outcome in self.outcomes
        )

    @property
    def unresolved(self) -> int:
        return sum(
            outcome.result.status is ReachabilityStatus.UNRESOLVED
            for outcome in self.outcomes
        )

    @property
    def unsupported(self) -> int:
        return sum(
            outcome.result.status is ReachabilityStatus.UNSUPPORTED
            for outcome in self.outcomes
        )

    @property
    def true_world_survival_rate(self) -> float:
        if not self.outcomes:
            return 1.0
        return self.survived / self.total

    @property
    def sound(self) -> bool:
        return self.false_exclusions == 0

    def summary(self) -> dict[str, Any]:
        return {
            "total": self.total,
            "survived": self.survived,
            "false_exclusions": self.false_exclusions,
            "witnessed": self.witnessed,
            "unresolved": self.unresolved,
            "unsupported": self.unsupported,
            "true_world_survival_rate": self.true_world_survival_rate,
            "sound": self.sound,
        }


ReachabilityEvaluator = Callable[..., ReachabilityResult]


def _sha256_json(value: object) -> str:
    payload = json.dumps(
        value,
        sort_keys=True,
        separators=(",", ":"),
        ensure_ascii=True,
    ).encode("utf-8")
    return "sha256:" + hashlib.sha256(payload).hexdigest()


def generate_true_world_transition(
    worker: SoundnessWorker,
    *,
    case_id: str,
    source: str,
    state: dict[str, Any],
    side: str,
    p1_choice: str,
    p2_choice: str,
    actual_rng_seed: str | None,
    probe_rng_seed: str | None,
    previews: dict[str, list[str]] | None = None,
) -> tuple[TrueWorldTransition, dict[str, Any]]:
    """Generate one known-real transition with the pinned Showdown runtime.

    Returns both the immutable test case and the exact child state so callers can
    chain multiple true-world decision boundaries.
    """

    if side not in {"p1", "p2"}:
        raise ValueError("true-world generation side must be p1 or p2")
    if not isinstance(state, dict) or not state:
        raise ValueError("true-world generation requires a serialized state")

    branch: dict[str, Any] = {
        "p1_choice": p1_choice,
        "p2_choice": p2_choice,
        "include_state": True,
        "view_side": side,
        "include_rng_draw_count": True,
        "rng_seed": actual_rng_seed,
    }
    if previews is not None:
        branch["previews"] = previews

    resolved = worker.branch_many(state=state, branches=[branch])
    if len(resolved) != 1 or resolved[0].get("index") != 0:
        raise RecoverySoundnessError(
            "true-world generator returned an invalid branch batch"
        )

    result = resolved[0]
    child_state = result.get("state")
    public_view = result.get("view")
    draw_count = result.get("rng_draw_count")
    if not isinstance(child_state, dict) or not child_state:
        raise RecoverySoundnessError(
            "true-world generator omitted the exact child state"
        )
    if not isinstance(public_view, dict):
        raise RecoverySoundnessError(
            "true-world generator omitted the public observation"
        )
    if (
        isinstance(draw_count, bool)
        or not isinstance(draw_count, int)
        or draw_count < 0
    ):
        raise RecoverySoundnessError(
            "true-world generator omitted a valid PRNG draw count"
        )

    transition = TrueWorldTransition(
        case_id=case_id,
        source=source,
        side=side,
        pre_state=state,
        p1_choice=p1_choice,
        p2_choice=p2_choice,
        actual_public_view=public_view,
        actual_rng_seed=actual_rng_seed,
        probe_rng_seed=probe_rng_seed,
        actual_rng_draw_count=draw_count,
        previews=previews,
    )
    return transition, child_state


def evaluate_true_world_transition(
    worker: SoundnessWorker,
    transition: TrueWorldTransition,
    *,
    evaluator: ReachabilityEvaluator = evaluate_deterministic_public_transition,
) -> TrueWorldTransitionOutcome:
    """Ask current exclusion authority whether one known-real world survives."""

    step = PublicReachabilityStep(
        p1_choice=transition.p1_choice,
        p2_choice=transition.p2_choice,
        expected_public_view=transition.actual_public_view,
        rng_seeds=(transition.probe_rng_seed,),
    )
    result = evaluator(
        worker,
        state=transition.pre_state,
        side=transition.side,
        step=step,
        previews=transition.previews,
    )
    return TrueWorldTransitionOutcome(
        transition=transition,
        result=result,
    )


def evaluate_true_world_suite(
    worker: SoundnessWorker,
    transitions: Iterable[TrueWorldTransition],
    *,
    evaluator: ReachabilityEvaluator = evaluate_deterministic_public_transition,
) -> RecoverySoundnessReport:
    """Evaluate a sequence/corpus of known-real hidden-world transitions."""

    outcomes = tuple(
        evaluate_true_world_transition(
            worker,
            transition,
            evaluator=evaluator,
        )
        for transition in transitions
    )
    return RecoverySoundnessReport(outcomes=outcomes)


def _coverage_json(result: ReachabilityResult) -> dict[str, Any] | None:
    if result.coverage is None:
        return None
    return asdict(result.coverage)


def false_exclusion_payload(
    outcome: TrueWorldTransitionOutcome,
) -> dict[str, Any]:
    """Return a complete deterministic regression payload for one false exclusion."""

    if not outcome.false_exclusion:
        raise ValueError(
            "only false exclusions may be serialized as hard regressions"
        )
    transition = outcome.transition
    return {
        "schema": "recovery-true-world-regression-v1",
        "case_id": transition.case_id,
        "source": transition.source,
        "state_fingerprint": transition.state_fingerprint,
        "side": transition.side,
        "pre_state": transition.pre_state,
        "p1_choice": transition.p1_choice,
        "p2_choice": transition.p2_choice,
        "actual_public_view": transition.actual_public_view,
        "actual_rng_seed": transition.actual_rng_seed,
        "probe_rng_seed": transition.probe_rng_seed,
        "actual_rng_draw_count": transition.actual_rng_draw_count,
        "previews": transition.previews,
        "reachability": {
            "status": outcome.result.status.value,
            "reason": outcome.result.reason,
            "witness_ids": list(outcome.result.witness_ids),
            "coverage": _coverage_json(outcome.result),
        },
    }


def write_false_exclusion_regressions(
    report: RecoverySoundnessReport,
    *,
    output_dir: str | Path,
) -> tuple[Path, ...]:
    """Persist every false exclusion atomically as a self-contained JSON case."""

    root = Path(output_dir).expanduser().resolve()
    root.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []

    for outcome in report.outcomes:
        if not outcome.false_exclusion:
            continue
        payload = false_exclusion_payload(outcome)
        safe_id = hashlib.sha256(
            outcome.transition.case_id.encode("utf-8")
        ).hexdigest()[:12]
        path = root / f"{safe_id}.json"
        temporary = path.with_suffix(".json.part")
        temporary.write_text(
            json.dumps(
                payload,
                ensure_ascii=False,
                indent=2,
                sort_keys=True,
            )
            + "\n",
            encoding="utf-8",
        )
        os.replace(temporary, path)
        written.append(path)

    return tuple(written)
