"""Pinned public Showdown metadata used by reachability preflight.

Generated from Pokémon Showdown a5df8274e85b0889bf2a9b3422a08b39732374fc base data plus the Champions mod.
Only public identifiers/categories needed to validate playerView evidence live here.
"""

SHOWDOWN_PUBLIC_CATALOG_PIN = "a5df8274e85b0889bf2a9b3422a08b39732374fc"

MOVE_CATEGORIES = {
    "absorb": "Special",
    "accelerock": "Physical",
    "acid": "Special",
    "acidarmor": "Status",
    "aciddownpour": "Physical",
    "acidspray": "Special",
    "acrobatics": "Physical",
    "acupressure": "Status",
    "aerialace": "Physical",
    "aeroblast": "Special",
    "afteryou": "Status",
    "agility": "Status",
    "aircutter": "Special",
    "airslash": "Special",
    "alloutpummeling": "Physical",
    "alluringvoice": "Special",
    "allyswitch": "Status",
    "amnesia": "Status",
    "anchorshot": "Physical",
    "ancientpower": "Special",
    "appleacid": "Special",
    "aquacutter": "Physical",
    "aquajet": "Physical",
    "aquaring": "Status",
    "aquastep": "Physical",
    "aquatail": "Physical",
    "armorcannon": "Special",
    "armthrust": "Physical",
    "aromatherapy": "Status",
    "aromaticmist": "Status",
    "assist": "Status",
    "assurance": "Physical",
    "astonish": "Physical",
    "astralbarrage": "Special",
    "attackorder": "Physical",
    "attract": "Status",
    "aurasphere": "Special",
    "aurawheel": "Physical",
    "aurorabeam": "Special",
    "auroraveil": "Status",
    "autotomize": "Status",
    "avalanche": "Physical",
    "axekick": "Physical",
    "babydolleyes": "Status",
    "baddybad": "Special",
    "banefulbunker": "Status",
    "barbbarrage": "Physical",
    "barrage": "Physical",
    "barrier": "Status",
    "batonpass": "Status",
    "beakblast": "Physical",
    "beatup": "Physical",
    "behemothbash": "Physical",
    "behemothblade": "Physical",
    "belch": "Special",
    "bellydrum": "Status",
    "bestow": "Status",
    "bide": "Physical",
    "bind": "Physical",
    "bite": "Physical",
    "bitterblade": "Physical",
    "bittermalice": "Special",
    "blackholeeclipse": "Physical",
    "blastburn": "Special",
    "blazekick": "Physical",
    "blazingtorque": "Physical",
    "bleakwindstorm": "Special",
    "blizzard": "Special",
    "block": "Status",
    "bloodmoon": "Special",
    "bloomdoom": "Physical",
    "blueflare": "Special",
    "bodypress": "Physical",
    "bodyslam": "Physical",
    "boltbeak": "Physical",
    "boltstrike": "Physical",
    "boneclub": "Physical",
    "bonemerang": "Physical",
    "bonerush": "Physical",
    "boomburst": "Special",
    "bounce": "Physical",
    "bouncybubble": "Special",
    "branchpoke": "Physical",
    "bravebird": "Physical",
    "breakingswipe": "Physical",
    "breakneckblitz": "Physical",
    "brickbreak": "Physical",
    "brine": "Special",
    "brutalswing": "Physical",
    "bubble": "Special",
    "bubblebeam": "Special",
    "bugbite": "Physical",
    "bugbuzz": "Special",
    "bulkup": "Status",
    "bulldoze": "Physical",
    "bulletpunch": "Physical",
    "bulletseed": "Physical",
    "burningbulwark": "Status",
    "burningjealousy": "Special",
    "burnup": "Special",
    "buzzybuzz": "Special",
    "calmmind": "Status",
    "camouflage": "Status",
    "captivate": "Status",
    "catastropika": "Physical",
    "ceaselessedge": "Physical",
    "celebrate": "Status",
    "charge": "Status",
    "chargebeam": "Special",
    "charm": "Status",
    "chatter": "Special",
    "chillingwater": "Special",
    "chillyreception": "Status",
    "chipaway": "Physical",
    "chloroblast": "Special",
    "circlethrow": "Physical",
    "clamp": "Physical",
    "clangingscales": "Special",
    "clangoroussoul": "Status",
    "clangoroussoulblaze": "Special",
    "clearsmog": "Special",
    "closecombat": "Physical",
    "coaching": "Status",
    "coil": "Status",
    "collisioncourse": "Physical",
    "combattorque": "Physical",
    "cometpunch": "Physical",
    "comeuppance": "Physical",
    "confide": "Status",
    "confuseray": "Status",
    "confusion": "Special",
    "constrict": "Physical",
    "continentalcrush": "Physical",
    "conversion": "Status",
    "conversion2": "Status",
    "copycat": "Status",
    "coreenforcer": "Special",
    "corkscrewcrash": "Physical",
    "corrosivegas": "Status",
    "cosmicpower": "Status",
    "cottonguard": "Status",
    "cottonspore": "Status",
    "counter": "Physical",
    "courtchange": "Status",
    "covet": "Physical",
    "crabhammer": "Physical",
    "craftyshield": "Status",
    "crosschop": "Physical",
    "crosspoison": "Physical",
    "crunch": "Physical",
    "crushclaw": "Physical",
    "crushgrip": "Physical",
    "curse": "Status",
    "cut": "Physical",
    "darkestlariat": "Physical",
    "darkpulse": "Special",
    "darkvoid": "Status",
    "dazzlinggleam": "Special",
    "decorate": "Status",
    "defendorder": "Status",
    "defensecurl": "Status",
    "defog": "Status",
    "destinybond": "Status",
    "detect": "Status",
    "devastatingdrake": "Physical",
    "diamondstorm": "Physical",
    "dig": "Physical",
    "direclaw": "Physical",
    "disable": "Status",
    "disarmingvoice": "Special",
    "discharge": "Special",
    "dive": "Physical",
    "dizzypunch": "Physical",
    "doodle": "Status",
    "doomdesire": "Special",
    "doubleedge": "Physical",
    "doublehit": "Physical",
    "doubleironbash": "Physical",
    "doublekick": "Physical",
    "doubleshock": "Physical",
    "doubleslap": "Physical",
    "doubleteam": "Status",
    "dracometeor": "Special",
    "dragonascent": "Physical",
    "dragonbreath": "Special",
    "dragoncheer": "Status",
    "dragonclaw": "Physical",
    "dragondance": "Status",
    "dragondarts": "Physical",
    "dragonenergy": "Special",
    "dragonhammer": "Physical",
    "dragonpulse": "Special",
    "dragonrage": "Special",
    "dragonrush": "Physical",
    "dragontail": "Physical",
    "drainingkiss": "Special",
    "drainpunch": "Physical",
    "dreameater": "Special",
    "drillpeck": "Physical",
    "drillrun": "Physical",
    "drumbeating": "Physical",
    "dualchop": "Physical",
    "dualwingbeat": "Physical",
    "dynamaxcannon": "Special",
    "dynamicpunch": "Physical",
    "earthpower": "Special",
    "earthquake": "Physical",
    "echoedvoice": "Special",
    "eerieimpulse": "Status",
    "eeriespell": "Special",
    "eggbomb": "Physical",
    "electricterrain": "Status",
    "electrify": "Status",
    "electroball": "Special",
    "electrodrift": "Special",
    "electroshot": "Special",
    "electroweb": "Special",
    "embargo": "Status",
    "ember": "Special",
    "encore": "Status",
    "endeavor": "Physical",
    "endure": "Status",
    "energyball": "Special",
    "entrainment": "Status",
    "eruption": "Special",
    "esperwing": "Special",
    "eternabeam": "Special",
    "expandingforce": "Special",
    "explosion": "Physical",
    "extrasensory": "Special",
    "extremeevoboost": "Status",
    "extremespeed": "Physical",
    "facade": "Physical",
    "fairylock": "Status",
    "fairywind": "Special",
    "fakeout": "Physical",
    "faketears": "Status",
    "falsesurrender": "Physical",
    "falseswipe": "Physical",
    "featherdance": "Status",
    "feint": "Physical",
    "feintattack": "Physical",
    "fellstinger": "Physical",
    "ficklebeam": "Special",
    "fierydance": "Special",
    "fierywrath": "Special",
    "filletaway": "Status",
    "finalgambit": "Special",
    "fireblast": "Special",
    "firefang": "Physical",
    "firelash": "Physical",
    "firepledge": "Special",
    "firepunch": "Physical",
    "firespin": "Special",
    "firstimpression": "Physical",
    "fishiousrend": "Physical",
    "fissure": "Physical",
    "flail": "Physical",
    "flameburst": "Special",
    "flamecharge": "Physical",
    "flamethrower": "Special",
    "flamewheel": "Physical",
    "flareblitz": "Physical",
    "flash": "Status",
    "flashcannon": "Special",
    "flatter": "Status",
    "fleurcannon": "Special",
    "fling": "Physical",
    "flipturn": "Physical",
    "floatyfall": "Physical",
    "floralhealing": "Status",
    "flowershield": "Status",
    "flowertrick": "Physical",
    "fly": "Physical",
    "flyingpress": "Physical",
    "focusblast": "Special",
    "focusenergy": "Status",
    "focuspunch": "Physical",
    "followme": "Status",
    "forcepalm": "Physical",
    "foresight": "Status",
    "forestscurse": "Status",
    "foulplay": "Physical",
    "freezedry": "Special",
    "freezeshock": "Physical",
    "freezingglare": "Special",
    "freezyfrost": "Special",
    "frenzyplant": "Special",
    "frostbreath": "Special",
    "frustration": "Physical",
    "furyattack": "Physical",
    "furycutter": "Physical",
    "furyswipes": "Physical",
    "fusionbolt": "Physical",
    "fusionflare": "Special",
    "futuresight": "Special",
    "gastroacid": "Status",
    "geargrind": "Physical",
    "gearup": "Status",
    "genesissupernova": "Special",
    "geomancy": "Status",
    "gigadrain": "Special",
    "gigaimpact": "Physical",
    "gigatonhammer": "Physical",
    "gigavolthavoc": "Physical",
    "glaciallance": "Physical",
    "glaciate": "Special",
    "glaiverush": "Physical",
    "glare": "Status",
    "glitzyglow": "Special",
    "gmaxbefuddle": "Physical",
    "gmaxcannonade": "Physical",
    "gmaxcentiferno": "Physical",
    "gmaxchistrike": "Physical",
    "gmaxcuddle": "Physical",
    "gmaxdepletion": "Physical",
    "gmaxdrumsolo": "Physical",
    "gmaxfinale": "Physical",
    "gmaxfireball": "Physical",
    "gmaxfoamburst": "Physical",
    "gmaxgoldrush": "Physical",
    "gmaxgravitas": "Physical",
    "gmaxhydrosnipe": "Physical",
    "gmaxmalodor": "Physical",
    "gmaxmeltdown": "Physical",
    "gmaxoneblow": "Physical",
    "gmaxrapidflow": "Physical",
    "gmaxreplenish": "Physical",
    "gmaxresonance": "Physical",
    "gmaxsandblast": "Physical",
    "gmaxsmite": "Physical",
    "gmaxsnooze": "Physical",
    "gmaxsteelsurge": "Physical",
    "gmaxstonesurge": "Physical",
    "gmaxstunshock": "Physical",
    "gmaxsweetness": "Physical",
    "gmaxtartness": "Physical",
    "gmaxterror": "Physical",
    "gmaxvinelash": "Physical",
    "gmaxvolcalith": "Physical",
    "gmaxvoltcrash": "Physical",
    "gmaxwildfire": "Physical",
    "gmaxwindrage": "Physical",
    "grassknot": "Special",
    "grasspledge": "Special",
    "grasswhistle": "Status",
    "grassyglide": "Physical",
    "grassyterrain": "Status",
    "gravapple": "Physical",
    "gravity": "Status",
    "growl": "Status",
    "growth": "Status",
    "grudge": "Status",
    "guardianofalola": "Special",
    "guardsplit": "Status",
    "guardswap": "Status",
    "guillotine": "Physical",
    "gunkshot": "Physical",
    "gust": "Special",
    "gyroball": "Physical",
    "hail": "Status",
    "hammerarm": "Physical",
    "happyhour": "Status",
    "harden": "Status",
    "hardpress": "Physical",
    "haze": "Status",
    "headbutt": "Physical",
    "headcharge": "Physical",
    "headlongrush": "Physical",
    "headsmash": "Physical",
    "healbell": "Status",
    "healblock": "Status",
    "healingwish": "Status",
    "healorder": "Status",
    "healpulse": "Status",
    "heartstamp": "Physical",
    "heartswap": "Status",
    "heatcrash": "Physical",
    "heatwave": "Special",
    "heavyslam": "Physical",
    "helpinghand": "Status",
    "hex": "Special",
    "hiddenpower": "Special",
    "hiddenpowerbug": "Special",
    "hiddenpowerdark": "Special",
    "hiddenpowerdragon": "Special",
    "hiddenpowerelectric": "Special",
    "hiddenpowerfighting": "Special",
    "hiddenpowerfire": "Special",
    "hiddenpowerflying": "Special",
    "hiddenpowerghost": "Special",
    "hiddenpowergrass": "Special",
    "hiddenpowerground": "Special",
    "hiddenpowerice": "Special",
    "hiddenpowerpoison": "Special",
    "hiddenpowerpsychic": "Special",
    "hiddenpowerrock": "Special",
    "hiddenpowersteel": "Special",
    "hiddenpowerwater": "Special",
    "highhorsepower": "Physical",
    "highjumpkick": "Physical",
    "holdback": "Physical",
    "holdhands": "Status",
    "honeclaws": "Status",
    "hornattack": "Physical",
    "horndrill": "Physical",
    "hornleech": "Physical",
    "howl": "Status",
    "hurricane": "Special",
    "hydrocannon": "Special",
    "hydropump": "Special",
    "hydrosteam": "Special",
    "hydrovortex": "Physical",
    "hyperbeam": "Special",
    "hyperdrill": "Physical",
    "hyperfang": "Physical",
    "hyperspacefury": "Physical",
    "hyperspacehole": "Special",
    "hypervoice": "Special",
    "hypnosis": "Status",
    "iceball": "Physical",
    "icebeam": "Special",
    "iceburn": "Special",
    "icefang": "Physical",
    "icehammer": "Physical",
    "icepunch": "Physical",
    "iceshard": "Physical",
    "icespinner": "Physical",
    "iciclecrash": "Physical",
    "iciclespear": "Physical",
    "icywind": "Special",
    "imprison": "Status",
    "incinerate": "Special",
    "infernalparade": "Special",
    "inferno": "Special",
    "infernooverdrive": "Physical",
    "infestation": "Special",
    "ingrain": "Status",
    "instruct": "Status",
    "iondeluge": "Status",
    "irondefense": "Status",
    "ironhead": "Physical",
    "irontail": "Physical",
    "ivycudgel": "Physical",
    "jawlock": "Physical",
    "jetpunch": "Physical",
    "judgment": "Special",
    "jumpkick": "Physical",
    "junglehealing": "Status",
    "karatechop": "Physical",
    "kinesis": "Status",
    "kingsshield": "Status",
    "knockoff": "Physical",
    "kowtowcleave": "Physical",
    "landswrath": "Physical",
    "laserfocus": "Status",
    "lashout": "Physical",
    "lastresort": "Physical",
    "lastrespects": "Physical",
    "lavaplume": "Special",
    "leafage": "Physical",
    "leafblade": "Physical",
    "leafstorm": "Special",
    "leaftornado": "Special",
    "leechlife": "Physical",
    "leechseed": "Status",
    "leer": "Status",
    "letssnuggleforever": "Physical",
    "lick": "Physical",
    "lifedew": "Status",
    "lightofruin": "Special",
    "lightscreen": "Status",
    "lightthatburnsthesky": "Special",
    "liquidation": "Physical",
    "lockon": "Status",
    "lovelykiss": "Status",
    "lowkick": "Physical",
    "lowsweep": "Physical",
    "luckychant": "Status",
    "luminacrash": "Special",
    "lunarblessing": "Status",
    "lunardance": "Status",
    "lunge": "Physical",
    "lusterpurge": "Special",
    "machpunch": "Physical",
    "magicalleaf": "Special",
    "magicaltorque": "Physical",
    "magiccoat": "Status",
    "magicpowder": "Status",
    "magicroom": "Status",
    "magmastorm": "Special",
    "magnetbomb": "Physical",
    "magneticflux": "Status",
    "magnetrise": "Status",
    "magnitude": "Physical",
    "makeitrain": "Special",
    "maliciousmoonsault": "Physical",
    "malignantchain": "Special",
    "matblock": "Status",
    "matchagotcha": "Special",
    "maxairstream": "Physical",
    "maxdarkness": "Physical",
    "maxflare": "Physical",
    "maxflutterby": "Physical",
    "maxgeyser": "Physical",
    "maxguard": "Status",
    "maxhailstorm": "Physical",
    "maxknuckle": "Physical",
    "maxlightning": "Physical",
    "maxmindstorm": "Physical",
    "maxooze": "Physical",
    "maxovergrowth": "Physical",
    "maxphantasm": "Physical",
    "maxquake": "Physical",
    "maxrockfall": "Physical",
    "maxstarfall": "Physical",
    "maxsteelspike": "Physical",
    "maxstrike": "Physical",
    "maxwyrmwind": "Physical",
    "meanlook": "Status",
    "meditate": "Status",
    "mefirst": "Status",
    "megadrain": "Special",
    "megahorn": "Physical",
    "megakick": "Physical",
    "megapunch": "Physical",
    "memento": "Status",
    "menacingmoonrazemaelstrom": "Special",
    "metalburst": "Physical",
    "metalclaw": "Physical",
    "metalsound": "Status",
    "meteorassault": "Physical",
    "meteorbeam": "Special",
    "meteormash": "Physical",
    "metronome": "Status",
    "mightycleave": "Physical",
    "milkdrink": "Status",
    "mimic": "Status",
    "mindblown": "Special",
    "mindreader": "Status",
    "minimize": "Status",
    "miracleeye": "Status",
    "mirrorcoat": "Special",
    "mirrormove": "Status",
    "mirrorshot": "Special",
    "mist": "Status",
    "mistball": "Special",
    "mistyexplosion": "Special",
    "mistyterrain": "Status",
    "moonblast": "Special",
    "moongeistbeam": "Special",
    "moonlight": "Status",
    "morningsun": "Status",
    "mortalspin": "Physical",
    "mountaingale": "Physical",
    "mudbomb": "Special",
    "muddywater": "Special",
    "mudshot": "Special",
    "mudslap": "Special",
    "mudsport": "Status",
    "multiattack": "Physical",
    "mysticalfire": "Special",
    "mysticalpower": "Special",
    "nastyplot": "Status",
    "naturalgift": "Physical",
    "naturepower": "Status",
    "naturesmadness": "Special",
    "needlearm": "Physical",
    "neverendingnightmare": "Physical",
    "nightdaze": "Special",
    "nightmare": "Status",
    "nightshade": "Special",
    "nightslash": "Physical",
    "nihillight": "Special",
    "nobleroar": "Status",
    "noretreat": "Status",
    "noxioustorque": "Physical",
    "nuzzle": "Physical",
    "oblivionwing": "Special",
    "obstruct": "Status",
    "oceanicoperetta": "Special",
    "octazooka": "Special",
    "octolock": "Status",
    "odorsleuth": "Status",
    "ominouswind": "Special",
    "orderup": "Physical",
    "originpulse": "Special",
    "outrage": "Physical",
    "overdrive": "Special",
    "overheat": "Special",
    "painsplit": "Status",
    "paleowave": "Special",
    "paraboliccharge": "Special",
    "partingshot": "Status",
    "payback": "Physical",
    "payday": "Physical",
    "peck": "Physical",
    "perishsong": "Status",
    "petalblizzard": "Physical",
    "petaldance": "Special",
    "phantomforce": "Physical",
    "photongeyser": "Special",
    "pikapapow": "Special",
    "pinmissile": "Physical",
    "plasmafists": "Physical",
    "playnice": "Status",
    "playrough": "Physical",
    "pluck": "Physical",
    "poisonfang": "Physical",
    "poisongas": "Status",
    "poisonjab": "Physical",
    "poisonpowder": "Status",
    "poisonsting": "Physical",
    "poisontail": "Physical",
    "polarflare": "Special",
    "pollenpuff": "Special",
    "poltergeist": "Physical",
    "populationbomb": "Physical",
    "pounce": "Physical",
    "pound": "Physical",
    "powder": "Status",
    "powdersnow": "Special",
    "powergem": "Special",
    "powershift": "Status",
    "powersplit": "Status",
    "powerswap": "Status",
    "powertrick": "Status",
    "powertrip": "Physical",
    "poweruppunch": "Physical",
    "powerwhip": "Physical",
    "precipiceblades": "Physical",
    "present": "Physical",
    "prismaticlaser": "Special",
    "protect": "Status",
    "psybeam": "Special",
    "psyblade": "Physical",
    "psychic": "Special",
    "psychicfangs": "Physical",
    "psychicnoise": "Special",
    "psychicterrain": "Status",
    "psychoboost": "Special",
    "psychocut": "Physical",
    "psychoshift": "Status",
    "psychup": "Status",
    "psyshieldbash": "Physical",
    "psyshock": "Special",
    "psystrike": "Special",
    "psywave": "Special",
    "pulverizingpancake": "Physical",
    "punishment": "Physical",
    "purify": "Status",
    "pursuit": "Physical",
    "pyroball": "Physical",
    "quash": "Status",
    "quickattack": "Physical",
    "quickguard": "Status",
    "quiverdance": "Status",
    "rage": "Physical",
    "ragefist": "Physical",
    "ragepowder": "Status",
    "ragingbull": "Physical",
    "ragingfury": "Physical",
    "raindance": "Status",
    "rapidspin": "Physical",
    "razorleaf": "Physical",
    "razorshell": "Physical",
    "razorwind": "Special",
    "recover": "Status",
    "recycle": "Status",
    "reflect": "Status",
    "reflecttype": "Status",
    "refresh": "Status",
    "relicsong": "Special",
    "rest": "Status",
    "retaliate": "Physical",
    "return": "Physical",
    "revelationdance": "Special",
    "revenge": "Physical",
    "reversal": "Physical",
    "revivalblessing": "Status",
    "risingvoltage": "Special",
    "roar": "Status",
    "roaroftime": "Special",
    "rockblast": "Physical",
    "rockclimb": "Physical",
    "rockpolish": "Status",
    "rockslide": "Physical",
    "rocksmash": "Physical",
    "rockthrow": "Physical",
    "rocktomb": "Physical",
    "rockwrecker": "Physical",
    "roleplay": "Status",
    "rollingkick": "Physical",
    "rollout": "Physical",
    "roost": "Status",
    "rototiller": "Status",
    "round": "Special",
    "ruination": "Special",
    "sacredfire": "Physical",
    "sacredsword": "Physical",
    "safeguard": "Status",
    "saltcure": "Physical",
    "sandattack": "Status",
    "sandsearstorm": "Special",
    "sandstorm": "Status",
    "sandtomb": "Physical",
    "sappyseed": "Physical",
    "savagespinout": "Physical",
    "scald": "Special",
    "scaleshot": "Physical",
    "scaryface": "Status",
    "scorchingsands": "Special",
    "scratch": "Physical",
    "screech": "Status",
    "searingshot": "Special",
    "searingsunrazesmash": "Physical",
    "secretpower": "Physical",
    "secretsword": "Special",
    "seedbomb": "Physical",
    "seedflare": "Special",
    "seismictoss": "Physical",
    "selfdestruct": "Physical",
    "shadowball": "Special",
    "shadowbone": "Physical",
    "shadowclaw": "Physical",
    "shadowforce": "Physical",
    "shadowpunch": "Physical",
    "shadowsneak": "Physical",
    "shadowstrike": "Physical",
    "sharpen": "Status",
    "shatteredpsyche": "Physical",
    "shedtail": "Status",
    "sheercold": "Special",
    "shellsidearm": "Special",
    "shellsmash": "Status",
    "shelltrap": "Special",
    "shelter": "Status",
    "shiftgear": "Status",
    "shockwave": "Special",
    "shoreup": "Status",
    "signalbeam": "Special",
    "silktrap": "Status",
    "silverwind": "Special",
    "simplebeam": "Status",
    "sing": "Status",
    "sinisterarrowraid": "Physical",
    "sizzlyslide": "Physical",
    "sketch": "Status",
    "skillswap": "Status",
    "skittersmack": "Physical",
    "skullbash": "Physical",
    "skyattack": "Physical",
    "skydrop": "Physical",
    "skyuppercut": "Physical",
    "slackoff": "Status",
    "slam": "Physical",
    "slash": "Physical",
    "sleeppowder": "Status",
    "sleeptalk": "Status",
    "sludge": "Special",
    "sludgebomb": "Special",
    "sludgewave": "Special",
    "smackdown": "Physical",
    "smartstrike": "Physical",
    "smellingsalts": "Physical",
    "smog": "Special",
    "smokescreen": "Status",
    "snaptrap": "Physical",
    "snarl": "Special",
    "snatch": "Status",
    "snipeshot": "Special",
    "snore": "Special",
    "snowscape": "Status",
    "soak": "Status",
    "softboiled": "Status",
    "solarbeam": "Special",
    "solarblade": "Physical",
    "sonicboom": "Special",
    "soulstealing7starstrike": "Physical",
    "spacialrend": "Special",
    "spark": "Physical",
    "sparklingaria": "Special",
    "sparklyswirl": "Special",
    "spectralthief": "Physical",
    "speedswap": "Status",
    "spicyextract": "Status",
    "spiderweb": "Status",
    "spikecannon": "Physical",
    "spikes": "Status",
    "spikyshield": "Status",
    "spinout": "Physical",
    "spiritbreak": "Physical",
    "spiritshackle": "Physical",
    "spite": "Status",
    "spitup": "Special",
    "splash": "Status",
    "splinteredstormshards": "Physical",
    "splishysplash": "Special",
    "spore": "Status",
    "spotlight": "Status",
    "springtidestorm": "Special",
    "stealthrock": "Status",
    "steameruption": "Special",
    "steamroller": "Physical",
    "steelbeam": "Special",
    "steelroller": "Physical",
    "steelwing": "Physical",
    "stickyweb": "Status",
    "stockpile": "Status",
    "stokedsparksurfer": "Special",
    "stomp": "Physical",
    "stompingtantrum": "Physical",
    "stoneaxe": "Physical",
    "stoneedge": "Physical",
    "storedpower": "Special",
    "stormthrow": "Physical",
    "strangesteam": "Special",
    "strength": "Physical",
    "strengthsap": "Status",
    "stringshot": "Status",
    "struggle": "Physical",
    "strugglebug": "Special",
    "stuffcheeks": "Status",
    "stunspore": "Status",
    "submission": "Physical",
    "substitute": "Status",
    "subzeroslammer": "Physical",
    "suckerpunch": "Physical",
    "sunnyday": "Status",
    "sunsteelstrike": "Physical",
    "supercellslam": "Physical",
    "superfang": "Physical",
    "superpower": "Physical",
    "supersonic": "Status",
    "supersonicskystrike": "Physical",
    "surf": "Special",
    "surgingstrikes": "Physical",
    "swagger": "Status",
    "swallow": "Status",
    "sweetkiss": "Status",
    "sweetscent": "Status",
    "swift": "Special",
    "switcheroo": "Status",
    "swordsdance": "Status",
    "synchronoise": "Special",
    "synthesis": "Status",
    "syrupbomb": "Special",
    "tachyoncutter": "Special",
    "tackle": "Physical",
    "tailglow": "Status",
    "tailslap": "Physical",
    "tailwhip": "Status",
    "tailwind": "Status",
    "takedown": "Physical",
    "takeheart": "Status",
    "tarshot": "Status",
    "taunt": "Status",
    "tearfullook": "Status",
    "teatime": "Status",
    "technoblast": "Special",
    "tectonicrage": "Physical",
    "teeterdance": "Status",
    "telekinesis": "Status",
    "teleport": "Status",
    "temperflare": "Physical",
    "terablast": "Special",
    "terastarstorm": "Special",
    "terrainpulse": "Special",
    "thief": "Physical",
    "thousandarrows": "Physical",
    "thousandwaves": "Physical",
    "thrash": "Physical",
    "throatchop": "Physical",
    "thunder": "Special",
    "thunderbolt": "Special",
    "thundercage": "Special",
    "thunderclap": "Special",
    "thunderfang": "Physical",
    "thunderouskick": "Physical",
    "thunderpunch": "Physical",
    "thundershock": "Special",
    "thunderwave": "Status",
    "tickle": "Status",
    "tidyup": "Status",
    "topsyturvy": "Status",
    "torchsong": "Special",
    "torment": "Status",
    "toxic": "Status",
    "toxicspikes": "Status",
    "toxicthread": "Status",
    "trailblaze": "Physical",
    "transform": "Status",
    "triattack": "Special",
    "trick": "Status",
    "trickortreat": "Status",
    "trickroom": "Status",
    "triplearrows": "Physical",
    "tripleaxel": "Physical",
    "tripledive": "Physical",
    "triplekick": "Physical",
    "tropkick": "Physical",
    "trumpcard": "Special",
    "twinbeam": "Special",
    "twineedle": "Physical",
    "twinkletackle": "Physical",
    "twister": "Special",
    "upperhand": "Physical",
    "uproar": "Special",
    "uturn": "Physical",
    "vacuumwave": "Special",
    "vcreate": "Physical",
    "veeveevolley": "Physical",
    "venomdrench": "Status",
    "venoshock": "Special",
    "victorydance": "Status",
    "vinewhip": "Physical",
    "visegrip": "Physical",
    "vitalthrow": "Physical",
    "voltswitch": "Special",
    "volttackle": "Physical",
    "wakeupslap": "Physical",
    "waterfall": "Physical",
    "watergun": "Special",
    "waterpledge": "Special",
    "waterpulse": "Special",
    "watershuriken": "Special",
    "watersport": "Status",
    "waterspout": "Special",
    "wavecrash": "Physical",
    "weatherball": "Special",
    "whirlpool": "Special",
    "whirlwind": "Status",
    "wickedblow": "Physical",
    "wickedtorque": "Physical",
    "wideguard": "Status",
    "wildboltstorm": "Special",
    "wildcharge": "Physical",
    "willowisp": "Status",
    "wingattack": "Physical",
    "wish": "Status",
    "withdraw": "Status",
    "wonderroom": "Status",
    "woodhammer": "Physical",
    "workup": "Status",
    "worryseed": "Status",
    "wrap": "Physical",
    "wringout": "Special",
    "xscissor": "Physical",
    "yawn": "Status",
    "zapcannon": "Special",
    "zenheadbutt": "Physical",
    "zingzap": "Physical",
    "zippyzap": "Physical",
}

MOVE_IDS = frozenset(MOVE_CATEGORIES)
ABILITY_IDS = frozenset(
    {
        "adaptability", "aerilate", "aftermath", "airlock", "analytic", "angerpoint", "angershell", "anticipation",
        "arenatrap", "armortail", "aromaveil", "asoneglastrier", "asonespectrier", "aurabreak", "auraguard", "baddreams",
        "ballfetch", "battery", "battlearmor", "battlebond", "beadsofruin", "beastboost", "berserk", "bigpecks",
        "blaze", "bulletproof", "cheekpouch", "chillingneigh", "chlorophyll", "clearbody", "cloudnine", "colorchange",
        "comatose", "commander", "competitive", "compoundeyes", "contrary", "corrosion", "costar", "cottondown",
        "cudchew", "curiousmedicine", "cursedbody", "cutecharm", "damp", "dancer", "darkaura", "dauntlessshield",
        "dazzling", "defeatist", "defiant", "deltastream", "desolateland", "disguise", "download", "dragonize",
        "dragonsmaw", "drizzle", "drought", "dryskin", "earlybird", "eartheater", "eelevate", "effectspore",
        "electricsurge", "electromorphosis", "embodyaspectcornerstone", "embodyaspecthearthflame", "embodyaspectteal", "embodyaspectwellspring", "emergencyexit", "fairyaura",
        "filter", "firemane", "flamebody", "flareboost", "flashfire", "flowergift", "flowerveil", "fluffy",
        "forecast", "forewarn", "friendguard", "frisk", "fullmetalbody", "furcoat", "galewings", "galvanize",
        "gluttony", "goodasgold", "gooey", "gorillatactics", "grasspelt", "grassysurge", "grimneigh", "guarddog",
        "gulpmissile", "guts", "hadronengine", "harvest", "healer", "heatproof", "heavymetal", "honeygather",
        "hospitality", "hugepower", "hungerswitch", "hustle", "hydration", "hypercutter", "icebody", "iceface",
        "icescales", "illuminate", "illusion", "immunity", "imposter", "infiltrator", "innardsout", "innerfocus",
        "insomnia", "intimidate", "intrepidsword", "ironbarbs", "ironfist", "justified", "keeneye", "klutz",
        "leafguard", "levitate", "libero", "lightmetal", "lightningrod", "limber", "lingeringaroma", "liquidooze",
        "liquidvoice", "longreach", "magicbounce", "magicguard", "magician", "magmaarmor", "magnetpull", "marvelscale",
        "megalauncher", "megasol", "merciless", "mimicry", "mindseye", "minus", "mirrorarmor", "mistysurge",
        "moldbreaker", "moody", "motordrive", "mountaineer", "moxie", "multiscale", "multitype", "mummy",
        "myceliummight", "naturalcure", "neuroforce", "neutralizinggas", "noability", "noguard", "normalize", "oblivious",
        "opportunist", "orichalcumpulse", "overcoat", "overgrow", "owntempo", "parentalbond", "pastelveil", "perishbody",
        "persistent", "pickpocket", "pickup", "piercingdrill", "pixilate", "plus", "poisonheal", "poisonpoint",
        "poisonpuppeteer", "poisontouch", "powerconstruct", "powerofalchemy", "powerspot", "prankster", "pressure", "primordialsea",
        "prismarmor", "propellertail", "protean", "protosynthesis", "psychicsurge", "punkrock", "purepower", "purifyingsalt",
        "quarkdrive", "queenlymajesty", "quickdraw", "quickfeet", "raindish", "rattled", "rebound", "receiver",
        "reckless", "refrigerate", "regenerator", "ripen", "rivalry", "rkssystem", "rockhead", "rockypayload",
        "roughskin", "runaway", "sandforce", "sandrush", "sandspit", "sandstream", "sandveil", "sapsipper",
        "schooling", "scrappy", "screencleaner", "seedsower", "serenegrace", "shadowshield", "shadowtag", "sharpness",
        "shedskin", "sheerforce", "shellarmor", "shielddust", "shieldsdown", "simple", "skilllink", "slowstart",
        "slushrush", "sniper", "snowcloak", "snowwarning", "solarpower", "solidrock", "soulheart", "soundproof",
        "speedboost", "spicyspray", "stakeout", "stall", "stalwart", "stamina", "stancechange", "static",
        "steadfast", "steamengine", "steelworker", "steelyspirit", "stench", "stickyhold", "stormdrain", "strongjaw",
        "sturdy", "suctioncups", "superluck", "supersweetsyrup", "supremeoverlord", "surgesurfer", "swarm", "sweetveil",
        "swiftswim", "swordofruin", "symbiosis", "synchronize", "tabletsofruin", "tangledfeet", "tanglinghair", "technician",
        "telepathy", "teraformzero", "terashell", "terashift", "teravolt", "thermalexchange", "thickfat", "tintedlens",
        "torrent", "toughclaws", "toxicboost", "toxicchain", "toxicdebris", "trace", "transistor", "triage",
        "truant", "turboblaze", "unaware", "unburden", "unnerve", "unseenfist", "vesselofruin", "victorystar",
        "vitalspirit", "voltabsorb", "wanderingspirit", "waterabsorb", "waterbubble", "watercompaction", "waterveil", "weakarmor",
        "wellbakedbody", "whitesmoke", "wimpout", "windpower", "windrider", "wonderguard", "wonderskin", "zenmode",
        "zerotohero",
    }
)

ITEM_IDS = frozenset(
    {
        "abilityshield", "abomasite", "absolite", "absolitez", "absorbbulb", "adamantcrystal", "adamantorb", "adrenalineorb",
        "aerodactylite", "aggronite", "aguavberry", "airballoon", "alakazite", "aloraichiumz", "altarianite", "ampharosite",
        "apicotberry", "armorfossil", "aspearberry", "assaultvest", "audinite", "auspiciousarmor", "babiriberry", "banettite",
        "barbaracite", "baxcalibrite", "beastball", "beedrillite", "belueberry", "berry", "berryjuice", "berrysweet",
        "berserkgene", "bignugget", "bigroot", "bindingband", "bitterberry", "blackbelt", "blackglasses", "blacksludge",
        "blastoisinite", "blazikenite", "blueorb", "blukberry", "blunderpolicy", "boosterenergy", "bottlecap", "brightpowder",
        "buggem", "buginiumz", "bugmemory", "burndrive", "burntberry", "cameruptite", "cellbattery", "chandelurite",
        "charcoal", "charizarditex", "charizarditey", "chartiberry", "cheriberry", "cherishball", "chesnaughtite", "chestoberry",
        "chilanberry", "chilldrive", "chimechite", "chippedpot", "choiceband", "choicescarf", "choicespecs", "chopleberry",
        "clawfossil", "clearamulet", "clefablite", "cloversweet", "cobaberry", "colburberry", "cornerstonemask", "cornnberry",
        "coverfossil", "covertcloak", "crabominite", "crackedpot", "crucibellite", "custapberry", "damprock", "darkgem",
        "darkiniumz", "darkmemory", "darkranite", "dawnstone", "decidiumz", "deepseascale", "deepseatooth", "delphoxite",
        "destinyknot", "diancite", "diveball", "domefossil", "dousedrive", "dracoplate", "dragalgite", "dragonfang",
        "dragongem", "dragoninite", "dragoniumz", "dragonmemory", "dragonscale", "drampanite", "dreadplate", "dreamball",
        "dubiousdisc", "durinberry", "duskball", "duskstone", "earthplate", "eelektrossite", "eeviumz", "ejectbutton",
        "ejectpack", "electirizer", "electricgem", "electricmemory", "electricseed", "electriumz", "emboarite", "enigmaberry",
        "eviolite", "excadrite", "expertbelt", "fairiumz", "fairyfeather", "fairygem", "fairymemory", "falinksite",
        "fastball", "feraligite", "fightinggem", "fightingmemory", "fightiniumz", "figyberry", "firegem", "firememory",
        "firestone", "firiumz", "fistplate", "flameorb", "flameplate", "floatstone", "floettite", "flowersweet",
        "flyinggem", "flyingmemory", "flyiniumz", "focusband", "focussash", "fossilizedbird", "fossilizeddino", "fossilizeddrake",
        "fossilizedfish", "friendball", "froslassite", "fullincense", "galaricacuff", "galaricawreath", "galladite", "ganlonberry",
        "garchompite", "garchompitez", "gardevoirite", "gengarite", "ghostgem", "ghostiumz", "ghostmemory", "glalitite",
        "glimmoranite", "goldberry", "goldbottlecap", "golisopite", "golurkite", "grassgem", "grassiumz", "grassmemory",
        "grassyseed", "greatball", "greninjite", "grepaberry", "gripclaw", "griseouscore", "griseousorb", "groundgem",
        "groundiumz", "groundmemory", "gyaradosite", "habanberry", "hardstone", "hawluchanite", "healball", "hearthflamemask",
        "heatranite", "heatrock", "heavyball", "heavydutyboots", "helixfossil", "heracronite", "hondewberry", "houndoominite",
        "iapapaberry", "iceberry", "icegem", "icememory", "icestone", "icicleplate", "iciumz", "icyrock",
        "inciniumz", "insectplate", "ironball", "ironplate", "jabocaberry", "jawfossil", "kangaskhanite", "kasibberry",
        "kebiaberry", "keeberry", "kelpsyberry", "kingsrock", "kommoniumz", "laggingtail", "lansatberry", "latiasite",
        "latiosite", "laxincense", "leafstone", "leek", "leftovers", "leppaberry", "levelball", "liechiberry",
        "lifeorb", "lightball", "lightclay", "loadeddice", "lopunnite", "loveball", "lovesweet", "lucarionite",
        "lucarionitez", "luckypunch", "lumberry", "luminousmoss", "lunaliumz", "lureball", "lustrousglobe", "lustrousorb",
        "luxuryball", "lycaniumz", "machobrace", "magearnite", "magmarizer", "magnet", "magoberry", "magostberry",
        "mail", "malamarite", "maliciousarmor", "manectite", "marangaberry", "marshadiumz", "masterball", "masterpieceteacup",
        "mawilite", "meadowplate", "medichamite", "meganiumite", "mentalherb", "meowsticite", "metagrossite", "metalalloy",
        "metalcoat", "metalpowder", "metronome", "mewniumz", "mewtwonitex", "mewtwonitey", "micleberry", "mimikiumz",
        "mindplate", "mintberry", "miracleberry", "miracleseed", "mirrorherb", "mistyseed", "moonball", "moonstone",
        "muscleband", "mysteryberry", "mysticwater", "nanabberry", "nestball", "netball", "nevermeltice", "nomelberry",
        "normalgem", "normaliumz", "occaberry", "oddincense", "oldamber", "oranberry", "ovalstone", "pamtreberry",
        "parkball", "passhoberry", "payapaberry", "pechaberry", "persimberry", "petayaberry", "pidgeotite", "pikaniumz",
        "pikashuniumz", "pinapberry", "pinkbow", "pinsirite", "pixieplate", "plumefossil", "poisonbarb", "poisongem",
        "poisoniumz", "poisonmemory", "pokeball", "polkadotbow", "pomegberry", "poweranklet", "powerband", "powerbelt",
        "powerbracer", "powerherb", "powerlens", "powerweight", "premierball", "prettyfeather", "primariumz", "prismscale",
        "protectivepads", "protector", "przcureberry", "psncureberry", "psychicgem", "psychicmemory", "psychicseed", "psychiumz",
        "punchingglove", "pyroarite", "qualotberry", "quickball", "quickclaw", "quickpowder", "rabutaberry", "raichunitex",
        "raichunitey", "rarebone", "rawstberry", "razorclaw", "razorfang", "razzberry", "reapercloth", "redcard",
        "redorb", "repeatball", "ribbonsweet", "rindoberry", "ringtarget", "rockgem", "rockincense", "rockiumz",
        "rockmemory", "rockyhelmet", "roomservice", "rootfossil", "roseincense", "roseliberry", "rowapberry", "rustedshield",
        "rustedsword", "sablenite", "sachet", "safariball", "safetygoggles", "sailfossil", "salacberry", "salamencite",
        "sceptilite", "scizorite", "scolipite", "scopelens", "scovillainite", "scraftinite", "seaincense", "sharpbeak",
        "sharpedonite", "shedshell", "shellbell", "shinystone", "shockdrive", "shucaberry", "silkscarf", "silverpowder",
        "sitrusberry", "skarmorite", "skullfossil", "skyplate", "slowbronite", "smoothrock", "snorliumz", "snowball",
        "softsand", "solganiumz", "souldew", "spelltag", "spelonberry", "splashplate", "spookyplate", "sportball",
        "staraptite", "starfberry", "starminite", "starsweet", "steelgem", "steeliumz", "steelixite", "steelmemory",
        "stick", "stickybarb", "stoneplate", "strangeball", "strawberrysweet", "sunstone", "swampertite", "sweetapple",
        "syrupyapple", "tamatoberry", "tangaberry", "tapuniumz", "tartapple", "tatsugirinite", "terrainextender", "thickclub",
        "throatspray", "thunderstone", "timerball", "toxicorb", "toxicplate", "tr00", "tr01", "tr02",
        "tr03", "tr04", "tr05", "tr06", "tr07", "tr08", "tr09", "tr10",
        "tr11", "tr12", "tr13", "tr14", "tr15", "tr16", "tr17", "tr18",
        "tr19", "tr20", "tr21", "tr22", "tr23", "tr24", "tr25", "tr26",
        "tr27", "tr28", "tr29", "tr30", "tr31", "tr32", "tr33", "tr34",
        "tr35", "tr36", "tr37", "tr38", "tr39", "tr40", "tr41", "tr42",
        "tr43", "tr44", "tr45", "tr46", "tr47", "tr48", "tr49", "tr50",
        "tr51", "tr52", "tr53", "tr54", "tr55", "tr56", "tr57", "tr58",
        "tr59", "tr60", "tr61", "tr62", "tr63", "tr64", "tr65", "tr66",
        "tr67", "tr68", "tr69", "tr70", "tr71", "tr72", "tr73", "tr74",
        "tr75", "tr76", "tr77", "tr78", "tr79", "tr80", "tr81", "tr82",
        "tr83", "tr84", "tr85", "tr86", "tr87", "tr88", "tr89", "tr90",
        "tr91", "tr92", "tr93", "tr94", "tr95", "tr96", "tr97", "tr98",
        "tr99", "twistedspoon", "tyranitarite", "ultraball", "ultranecroziumz", "unremarkableteacup", "upgrade", "utilityumbrella",
        "venusaurite", "victreebelite", "vilevial", "wacanberry", "watergem", "wateriumz", "watermemory", "waterstone",
        "watmelberry", "waveincense", "weaknesspolicy", "wellspringmask", "wepearberry", "whippeddream", "whiteherb", "widelens",
        "wikiberry", "wiseglasses", "yacheberry", "zapplate", "zeraorite", "zoomlens", "zygardite",
    }
)

CONDITION_IDS = frozenset(
    {
        "arceus", "brn", "choicelock", "commanded", "commanding", "confusion", "deltastream", "desolateland",
        "dynamax", "flinch", "frz", "futuremove", "gem", "hail", "healreplacement", "lockedmove",
        "mustrecharge", "par", "partiallytrapped", "primordialsea", "psn", "raindance", "rolloutstorage", "sandstorm",
        "silvally", "slp", "snowscape", "stall", "sunnyday", "tox", "trapped", "trapper",
        "twoturnmove", "zacian", "zamazenta",
    }
)


# Public protocol source labels that are not Dex table entries.
SPECIAL_EFFECT_IDS = frozenset(
    {
        "drain",
        "recoil",
        "gem",
    }
)
